# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwinodw.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import box1
import sys


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 60, 271, 61))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 230, 161, 61))
        self.pushButton.setObjectName("pushButton")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.open)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    # def open(self):
    #     print(123)
    #     self.m = Ui_box1_objectName()
    #     self.m.setupUi(MainWindow)
        # self.m.show()
        # MainWindow.show()
        # MainWindow.hide()

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.label.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">这是主窗口</span></p></body></html>"))
        self.pushButton.setText(_translate("Main", "next"))

# class Ui_box1_objectName(object):
#     def setupUi(self, box1_objectName):
#         box1_objectName.setObjectName("box1_objectName")
#         box1_objectName.resize(500, 500)
#         self.centralwidget = QtWidgets.QWidget(box1_objectName)
#         self.centralwidget.setObjectName("centralwidget")
#         self.label = QtWidgets.QLabel(self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(100, 70, 221, 81))
#         self.label.setObjectName("label")
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(120, 240, 121, 41))
#         self.pushButton.setObjectName("pushButton")
#         box1_objectName.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(box1_objectName)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
#         self.menubar.setObjectName("menubar")
#         box1_objectName.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(box1_objectName)
#         self.statusbar.setObjectName("statusbar")
#         box1_objectName.setStatusBar(self.statusbar)
#         self.pushButton.clicked.connect(self.back)
#
#         self.retranslateUi(box1_objectName)
#         QtCore.QMetaObject.connectSlotsByName(box1_objectName)
#
#     def back(self):
#         self.m = Ui_Main()
#         self.m.setupUi(MainWindow)
#
#     def retranslateUi(self, box1_objectName):
#         _translate = QtCore.QCoreApplication.translate
#         box1_objectName.setWindowTitle(_translate("box1_objectName", "MainWindow"))
#         self.label.setText(_translate("box1_objectName", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">这是副窗口！</span></p></body></html>"))
#         self.pushButton.setText(_translate("box1_objectName", "返回"))

# if __name__ == '__main__':
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()  # 创建窗体对象
#     ui = Ui_Main()  # 创建PyQt设计的窗体对象
#     ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置
#     MainWindow.show()  # 显示窗体
#     sys.exit(app.exec_())  # 程序关闭时退出进程