# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'box1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import main
import random


class Ui_MainWindow(object):
    def __init__(self):
        self.timer = QtCore.QTimer()
        # self.timer.timeout.connect(self.func)
        # self.timer.start(1000)
        # a = random.randint(0,10)
        # print('box1:'+str(a))

    def func(self):
        # pass
        # print('in box1')
        self.a = random.randint(0,10)
        # if self.a < 3:
        #     self.label.setText(
        #         "<html><head/><body><p><span style=\" font-size:28pt;\">温度：" + str(self.a) + "</span></p></body></html>")
        print('box1:'+str(self.a))
        # temp = random.randint(0, 10)
        # self.label.setText(
        #     "<html><head/><body><p><span style=\" font-size:28pt;\">温度：" + str(temp) + "</span></p></body></html>")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 110, 461, 221))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 400, 291, 81))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.back)

        # self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.func)
        self.timer.start(3000)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def back(self):
        pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:28pt;\">温度：</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "返回"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    box1Window = QtWidgets.QMainWindow()
    box1Ui = Ui_MainWindow()
    box1Ui.setupUi(box1Window)
    box1Window.show()
    sys.exit(app.exec_())
