# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import box1
import time


class Ui_MainWindow(object):
    def __init__(self):
        self.timer = QtCore.QTimer()
        # self.timer.timeout.connect(self.func)
        # self.timer.start(1000)

    def func(self):
        # print('in main')
        self.a = random.randint(0, 10)
        # if True:
        #     self.label.setText(
        #         "<html><head/><body><p><span style=\" font-size:28pt;\">" + str(self.a) + "</span></p></body></html>")
        print("main:" + str(self.a))
        # if random.random() < 0.5:
        #     self.label.setText(
        #         "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">正常？</span></p></body></html>")
        # else:
        #     self.label.setText(
        #         "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">正常</span></p></body></html>")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 360, 281, 111))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 110, 281, 151))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.showBox1)

        self.timer.timeout.connect(self.func)
        self.timer.start(3000)

        # self.timer = QtCore.QTimer()
        # self.timer.timeout.connect(self.func)
        # self.timer.start(1000)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def showBox1(self):
        pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "查看"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">正常</span></p></body></html>"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    mainUi = Ui_MainWindow()
    mainUi.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
