# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from random import random
import random
import sys
import dataSender


class Ui_MainWindow(object):
    '''
    frame_2:一号贮运箱,label,label_2,pushbutton
    frame_3:二号贮运箱,label_3,label_7,pushbutton_2
    frame_4:三号贮运箱,label_8,label_9,pushbutton_3
    frame_5:四号贮运箱,label_10,label_11,pushbutton_4
    frame_6:五号贮运箱,label_12,label_13,pushbutton_5
    frame_7:六号贮运箱,label_14,label-15,pushbutton_6
    '''

    def __init__(self):
        self.box1_abnormal = False
        self.box2_abnormal = False
        self.box3_abnormal = False
        self.box4_abnormal = False
        self.box5_abnormal = False
        self.box6_abnormal = False
        # self.box1StatusList = [0 for i in range(9)]
        # self.box2StatusList = [0 for i in range(9)]
        # self.box3StatusList = [0 for i in range(9)]
        # self.box4StatusList = [0 for i in range(9)]
        # self.box5StatusList = [0 for i in range(9)]
        # self.box6StatusList = [0 for i in range(9)]

    #     self.timer = QtCore.QTimer()
    #     self.timer.timeout.connect(self.show_time)
    #     self.timer.start(1000)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1200)
        MainWindow.setStyleSheet("background-color: rgb(21, 32, 42);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1921, 111))
        self.frame.setStyleSheet("background-color: rgb(25, 104, 179);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("image: url(:/jpg/images/logo.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_2.setStretch(2, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 150, 1821, 1001))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(50)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_3.setStyleSheet("color: rgb(140, 192, 222);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 40, 511, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                        "font: 20pt \"黑体\";\n"
                                        "color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 2)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_2.setStyleSheet("color: rgb(140, 192, 222);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 511, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                      "font: 20pt \"黑体\";\n"
                                      "color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_4.setStyleSheet("color: rgb(140, 192, 222);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 40, 511, 401))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                        "font: 20pt \"黑体\";\n"
                                        "color: rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 2)
        self.gridLayout.addWidget(self.frame_4, 0, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_5.setStyleSheet("color: rgb(140, 192, 222);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 40, 511, 401))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                        "font: 20pt \"黑体\";\n"
                                        "color: rgb(0, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_4.setStretch(0, 3)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_4.setStretch(2, 2)
        self.gridLayout.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_6.setStyleSheet("color: rgb(140, 192, 222);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(2)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 40, 511, 401))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                        "font: 20pt \"黑体\";\n"
                                        "color: rgb(0, 0, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_5.setStretch(0, 3)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(2, 2)
        self.gridLayout.addWidget(self.frame_6, 1, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_7.setStyleSheet("color: rgb(140, 192, 222);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(2)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frame_7)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(30, 40, 511, 401))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                        "font: 20pt \"黑体\";\n"
                                        "color: rgb(0, 0, 0);")
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_6.setStretch(0, 3)
        self.verticalLayout_6.setStretch(1, 2)
        self.verticalLayout_6.setStretch(2, 2)
        self.gridLayout.addWidget(self.frame_7, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.open1)  # 查看贮运箱1号具体参数的button
        self.pushButton_2.clicked.connect(self.open2)  # 查看贮运箱2号具体参数的button
        self.pushButton_3.clicked.connect(self.open3)  # 查看贮运箱3号具体参数的button
        self.pushButton_4.clicked.connect(self.open4)  # 查看贮运箱4号具体参数的button
        self.pushButton_5.clicked.connect(self.open5)  # 查看贮运箱5号具体参数的button
        self.pushButton_6.clicked.connect(self.open6)  # 查看贮运箱6号具体参数的button

        self.datetime = QtCore.QDateTime()
        # self.timer = QtCore.QTimer()
        self.timeTimer = QtCore.QTimer()
        self.dataTimer = QtCore.QTimer()
        self.timeTimer.timeout.connect(self.show_time)
        self.dataTimer.timeout.connect(self.recieve_data)
        # self.timer.timeout.connect(self.box1Status)
        # self.timer.timeout.connect(self.box2Status)
        # self.timer.timeout.connect(self.box3Status)
        # self.timer.timeout.connect(self.box4Status)
        # self.timer.timeout.connect(self.box5Status)
        # self.timer.timeout.connect(self.box6Status)
        self.timeTimer.start(1000)
        self.dataTimer.start(2000)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def recieve_data(self):
        data = dataSender.send_data()
        box_abnormal_flags = [self.box1_abnormal, self.box2_abnormal, self.box3_abnormal, self.box4_abnormal,
                              self.box5_abnormal, self.box6_abnormal]
        for i in range(6):
            l_list = []
            for j in range(9):
                if data[i][j] == 1:
                    l_list.append(j)
            if len(l_list) != 0 and (not box_abnormal_flags[i]):
                self.check_data(i, l_list)
            elif len(l_list) == 0 and box_abnormal_flags[i]:
                self.recover_window(i)

    def check_data(self, i, list_j):
        # 所有的环境参数
        data_dic = {0: '温度', 1: '箱外压力', 2: '氮气浓度', 3: '湿度', 4: '箱内外压力差', 5: '四氧化二氮浓度', 6: '箱内压力', 7: '电池电量',
                    8: '一甲基肼浓度'}

        # 贮运箱1号出问题了
        # frame_2: 一号贮运箱, label, label_2, pushbutton
        if i == 0:
            self.box1_abnormal = True
            # for j in list_j:
            #     self.box1StatusList[j] = 1
            error_text = '异常'
            if len(list_j) == 1:
                error_text = data_dic[list_j[0]] + ' ' + error_text
            else:
                for error in list_j:
                    error_text = data_dic[error] + ' ' + error_text
            self.frame_2.setStyleSheet("color: rgb(140, 192, 222);\n"
                                       "background-color: rgb(255, 163, 163);")
            self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(206, 0, 0);")
            self.pushButton.setStyleSheet("font: 20pt \"黑体\";\n"
                                          "background-color: rgb(255, 215, 215);\n"
                                          "color: rgb(255, 0, 0);")
            self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
            self.label_2.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">"+error_text+"</span></p></body></html>")


        # 贮运箱2号出问题了
        # frame_3: 二号贮运箱, label_3, label_7, pushbutton_2
        elif i == 1:
            self.box2_abnormal = True
            # for j in list_j:
            #     self.box2StatusList[j] = 1
            error_text = '异常'
            if len(list_j) == 1:
                error_text = data_dic[list_j[0]] + ' ' + error_text
            else:
                for error in list_j:
                    error_text = data_dic[error] + ' ' + error_text
            self.frame_3.setStyleSheet("color: rgb(140, 192, 222);\n"
                                       "background-color: rgb(255, 163, 163);")
            self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "background-color: rgb(206, 0, 0);")
            self.pushButton_2.setStyleSheet("font: 20pt \"黑体\";\n"
                                            "background-color: rgb(255, 215, 215);\n"
                                            "color: rgb(255, 0, 0);")
            self.label_7.setStyleSheet("color: rgb(255, 0, 0);")
            self.label_7.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">" + error_text + "</span></p></body></html>")

        # 贮运箱3号出问题了
        # frame_4: 三号贮运箱, label_8, label_9, pushbutton_3
        elif i == 2:
            self.box3_abnormal = True
            # for j in list_j:
            #     self.box3StatusList[j] = 1
            error_text = '异常'
            if len(list_j) == 1:
                error_text = data_dic[list_j[0]] + ' ' + error_text
            else:
                for error in list_j:
                    error_text = data_dic[error] + ' ' + error_text
            self.frame_4.setStyleSheet("color: rgb(140, 192, 222);\n"
                                       "background-color: rgb(255, 163, 163);")
            self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "background-color: rgb(206, 0, 0);")
            self.pushButton_3.setStyleSheet("font: 20pt \"黑体\";\n"
                                            "background-color: rgb(255, 215, 215);\n"
                                            "color: rgb(255, 0, 0);")
            self.label_9.setStyleSheet("color: rgb(255, 0, 0);")
            self.label_9.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">" + error_text + "</span></p></body></html>")

        # 贮运箱4号出问题了
        # frame_5: 四号贮运箱, label_10, label_11, pushbutton_4
        elif i == 3:
            self.box4_abnormal = True
            # for j in list_j:
            #     self.box4StatusList[j] = 1
            error_text = '异常'
            if len(list_j) == 1:
                error_text = data_dic[list_j[0]] + ' ' + error_text
            else:
                for error in list_j:
                    error_text = data_dic[error] + ' ' + error_text
            self.frame_5.setStyleSheet("color: rgb(140, 192, 222);\n"
                                       "background-color: rgb(255, 163, 163);")
            self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(206, 0, 0);")
            self.pushButton_4.setStyleSheet("font: 20pt \"黑体\";\n"
                                            "background-color: rgb(255, 215, 215);\n"
                                            "color: rgb(255, 0, 0);")
            self.label_11.setStyleSheet("color: rgb(255, 0, 0);")
            self.label_11.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">" + error_text + "</span></p></body></html>")

        # 贮运箱5号出问题了
        # frame_6: 五号贮运箱, label_12, label_13, pushbutton_5
        elif i == 4:
            self.box5_abnormal = True
            # for j in list_j:
            #     self.box5StatusList[j] = 1
            error_text = '异常'
            if len(list_j) == 1:
                error_text = data_dic[list_j[0]] + ' ' + error_text
            else:
                for error in list_j:
                    error_text = data_dic[error] + ' ' + error_text
            self.frame_6.setStyleSheet("color: rgb(140, 192, 222);\n"
                                       "background-color: rgb(255, 163, 163);")
            self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(206, 0, 0);")
            self.pushButton_5.setStyleSheet("font: 20pt \"黑体\";\n"
                                            "background-color: rgb(255, 215, 215);\n"
                                            "color: rgb(255, 0, 0);")
            self.label_13.setStyleSheet("color: rgb(255, 0, 0);")
            self.label_13.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">" + error_text + "</span></p></body></html>")

        # 贮运箱6号出问题了
        # frame_7: 六号贮运箱, label_14, label_15, pushbutton_6
        else:
            self.box6_abnormal = True
            # for j in list_j:
            #     self.box6StatusList[j] = 1
            error_text = '异常'
            if len(list_j) == 1:
                error_text = data_dic[list_j[0]] + ' ' + error_text
            else:
                for error in list_j:
                    error_text = data_dic[error] + ' ' + error_text
            self.frame_7.setStyleSheet("color: rgb(140, 192, 222);\n"
                                       "background-color: rgb(255, 163, 163);")
            self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(206, 0, 0);")
            self.pushButton_6.setStyleSheet("font: 20pt \"黑体\";\n"
                                            "background-color: rgb(255, 215, 215);\n"
                                            "color: rgb(255, 0, 0);")
            self.label_15.setStyleSheet("color: rgb(255, 0, 0);")
            self.label_15.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">" + error_text + "</span></p></body></html>")

    def recover_window(self, box):
        if box == 0:
            # self.box1StatusList = [0 for i in range(8)]
            self.frame_2.setStyleSheet("color: rgb(140, 192, 222);")
            self.label.setStyleSheet("color: rgb(140, 192, 222);")
            self.pushButton.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                          "font: 20pt \"黑体\";\n"
                                          "color: rgb(0, 0, 0);")
            self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
            self.label_2.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
            self.box1_abnormal = False
        elif box == 1:
            # self.box2StatusList = [0 for i in range(8)]
            self.frame_3.setStyleSheet("color: rgb(140, 192, 222);")
            self.label_3.setStyleSheet("color: rgb(140, 192, 222);")
            self.pushButton_2.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                            "font: 20pt \"黑体\";\n"
                                            "color: rgb(0, 0, 0);")
            self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
            self.label_7.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")

            self.box2_abnormal = False
        elif box == 2:
            # self.box3StatusList = [0 for i in range(8)]
            self.frame_4.setStyleSheet("color: rgb(140, 192, 222);")
            self.label_8.setStyleSheet("color: rgb(140, 192, 222);")
            self.pushButton_3.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                            "font: 20pt \"黑体\";\n"
                                            "color: rgb(0, 0, 0);")
            self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
            self.label_9.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")

            self.box3_abnormal = False
        elif box == 3:
            # self.box4StatusList = [0 for i in range(8)]
            self.frame_5.setStyleSheet("color: rgb(140, 192, 222);")
            self.label_10.setStyleSheet("color: rgb(140, 192, 222);")
            self.pushButton_4.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                            "font: 20pt \"黑体\";\n"
                                            "color: rgb(0, 0, 0);")
            self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
            self.label_11.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
            self.box4_abnormal = False
        elif box == 4:
            # self.box5StatusList = [0 for i in range(8)]
            self.frame_6.setStyleSheet("color: rgb(140, 192, 222);")
            self.label_12.setStyleSheet("color: rgb(140, 192, 222);")
            self.pushButton_5.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                            "font: 20pt \"黑体\";\n"
                                            "color: rgb(0, 0, 0);")
            self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
            self.label_13.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
            self.box5_abnormal = False
        else:
            # self.box6StatusList = [0 for i in range(8)]
            self.frame_7.setStyleSheet("color: rgb(140, 192, 222);")
            self.label_14.setStyleSheet("color: rgb(140, 192, 222);")
            self.pushButton_6.setStyleSheet("background-color: rgb(140, 192, 222);\n"
                                            "font: 20pt \"黑体\";\n"
                                            "color: rgb(0, 0, 0);")
            self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
            self.label_15.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
            self.box6_abnormal = False

    def show_time(self):
        text = self.datetime.currentDateTime().toString(QtCore.Qt.DefaultLocaleLongDate)
        self.label_6.setText(
            "<html><head/><body><p><span style=\" font-size:13pt; font-weight:200; color:#ffffff;\">" + text + "</span></p></body></html>")

    def open1(self):
        pass

    def open2(self):
        pass

    def open3(self):
        pass

    def open4(self):
        pass

    def open5(self):
        pass

    def open6(self):
        pass

    # # 一号贮运箱状态：frame_2,label,label_2,pushbutton
    # def box1Status(self):
    #     if (random.random() < 0.1):
    #         self.frame_2.setStyleSheet("color: rgb(140, 192, 222);\n"
    #                                    "background-color: rgb(255, 163, 163);")
    #         self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
    #                                  "background-color: rgb(206, 0, 0);")
    #         self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
    #         self.label_2.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">异常</span></p></body></html>")
    #         self.pushButton.setStyleSheet("font: 20pt \"黑体\";\n"
    #                                       "background-color: rgb(255, 215, 215);\n"
    #                                       "color: rgb(255, 0, 0);")
    #     else:
    #         self.frame_2.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
    #         self.label_2.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
    #         self.pushButton.setStyleSheet("background-color: rgb(140, 192, 222);\n"
    #                                       "font: 20pt \"黑体\";\n"
    #                                       "color: rgb(0, 0, 0);")
    #
    # # 二号贮运箱状态：frame_3,label_3,label_7,pushbutton_2
    # def box2Status(self):
    #     if (random.random() < 0.1):
    #         self.frame_3.setStyleSheet("color: rgb(140, 192, 222);\n"
    #                                    "background-color: rgb(255, 163, 163);")
    #         self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
    #                                    "background-color: rgb(206, 0, 0);")
    #         self.label_7.setStyleSheet("color: rgb(255, 0, 0);")
    #         self.label_7.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">异常</span></p></body></html>")
    #         self.pushButton_2.setStyleSheet("font: 20pt \"黑体\";\n"
    #                                         "background-color: rgb(255, 215, 215);\n"
    #                                         "color: rgb(255, 0, 0);")
    #     else:
    #         self.frame_3.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_3.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
    #         self.label_7.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
    #         self.pushButton_2.setStyleSheet("background-color: rgb(140, 192, 222);\n"
    #                                         "font: 20pt \"黑体\";\n"
    #                                         "color: rgb(0, 0, 0);")
    #
    # # 三号贮运箱状态：frame_4,label_8,label_9,pushbutton_3
    # def box3Status(self):
    #     if (random.random() < 0.1):
    #         self.frame_4.setStyleSheet("color: rgb(140, 192, 222);\n"
    #                                    "background-color: rgb(255, 163, 163);")
    #         self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
    #                                    "background-color: rgb(206, 0, 0);")
    #         self.label_9.setStyleSheet("color: rgb(255, 0, 0);")
    #         self.label_9.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">异常</span></p></body></html>")
    #         self.pushButton_3.setStyleSheet("font: 20pt \"黑体\";\n"
    #                                         "background-color: rgb(255, 215, 215);\n"
    #                                         "color: rgb(255, 0, 0);")
    #     else:
    #         self.frame_4.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_8.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
    #         self.label_9.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
    #         self.pushButton_3.setStyleSheet("background-color: rgb(140, 192, 222);\n"
    #                                         "font: 20pt \"黑体\";\n"
    #                                         "color: rgb(0, 0, 0);")
    #
    # # 四号贮运箱状态：frame_5,label_10,label_11,pushbutton_4
    # def box4Status(self):
    #     if (random.random() < 0.1):
    #         self.frame_5.setStyleSheet("color: rgb(140, 192, 222);\n"
    #                                    "background-color: rgb(255, 163, 163);")
    #         self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
    #                                     "background-color: rgb(206, 0, 0);")
    #         self.label_11.setStyleSheet("color: rgb(255, 0, 0);")
    #         self.label_11.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">异常</span></p></body></html>")
    #         self.pushButton_4.setStyleSheet("font: 20pt \"黑体\";\n"
    #                                         "background-color: rgb(255, 215, 215);\n"
    #                                         "color: rgb(255, 0, 0);")
    #     else:
    #         self.frame_5.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_10.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
    #         self.label_11.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
    #         self.pushButton_4.setStyleSheet("background-color: rgb(140, 192, 222);\n"
    #                                         "font: 20pt \"黑体\";\n"
    #                                         "color: rgb(0, 0, 0);")
    #
    # # 五号贮运箱状态：frame_6,label_12,label_13,pushbutton_5
    # def box5Status(self):
    #     if (random.random() < 0.1):
    #         self.frame_6.setStyleSheet("color: rgb(140, 192, 222);\n"
    #                                    "background-color: rgb(255, 163, 163);")
    #         self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
    #                                     "background-color: rgb(206, 0, 0);")
    #         self.label_13.setStyleSheet("color: rgb(255, 0, 0);")
    #         self.label_13.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">异常</span></p></body></html>")
    #         self.pushButton_5.setStyleSheet("font: 20pt \"黑体\";\n"
    #                                         "background-color: rgb(255, 215, 215);\n"
    #                                         "color: rgb(255, 0, 0);")
    #     else:
    #         self.frame_6.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_12.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
    #         self.label_13.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
    #         self.pushButton_5.setStyleSheet("background-color: rgb(140, 192, 222);\n"
    #                                         "font: 20pt \"黑体\";\n"
    #                                         "color: rgb(0, 0, 0);")
    #
    # # 六号贮运箱状态：frame_7,label_14,label_15,pushbutton_6
    # def box6Status(self):
    #     if (random.random() < 0.1):
    #         self.frame_7.setStyleSheet("color: rgb(140, 192, 222);\n"
    #                                    "background-color: rgb(255, 163, 163);")
    #         self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
    #                                     "background-color: rgb(206, 0, 0);")
    #         self.label_15.setStyleSheet("color: rgb(255, 0, 0);")
    #         self.label_15.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">异常</span></p></body></html>")
    #         self.pushButton_6.setStyleSheet("font: 20pt \"黑体\";\n"
    #                                         "background-color: rgb(255, 215, 215);\n"
    #                                         "color: rgb(255, 0, 0);")
    #     else:
    #         self.frame_7.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_14.setStyleSheet("color: rgb(140, 192, 222);")
    #         self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
    #         self.label_15.setText(
    #             "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>")
    #         self.pushButton_6.setStyleSheet("background-color: rgb(140, 192, 222);\n"
    #                                         "font: 20pt \"黑体\";\n"
    #                                         "color: rgb(0, 0, 0);")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">贮运设备环境参数监测显示系统</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:13pt; font-weight:200; color:#ffffff;\">(获取系统时间中...)</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:60pt; font-weight:1000;\">02</span><span style=\" font-size:24pt; font-weight:100;\">号 贮运箱</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "查看具体参数"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:60pt; font-weight:1000;\">01</span><span style=\" font-size:24pt; font-weight:100;\">号 贮运箱</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "查看具体参数"))
        self.label_8.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:60pt; font-weight:1000;\">03</span><span style=\" font-size:24pt; font-weight:100;\">号 贮运箱</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "查看具体参数"))
        self.label_10.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" font-size:60pt; font-weight:1000;\">04</span><span style=\" font-size:24pt; font-weight:100;\">号 贮运箱</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "查看具体参数"))
        self.label_12.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" font-size:60pt; font-weight:1000;\">05</span><span style=\" font-size:24pt; font-weight:100;\">号 贮运箱</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "查看具体参数"))
        self.label_14.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" font-size:60pt; font-weight:1000;\">06</span><span style=\" font-size:24pt; font-weight:100;\">号 贮运箱</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">运行正常</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "查看具体参数"))


import images_mainWindow_rc

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_MainWindow()  # 创建PyQt设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程
